RapidApi/RapidApiConsume.Web/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiConsume.Web.Models;

namespace RapidApiConsume.Web.Controllers
{
    public class BookingController : Controller
    {
        public async Task<IActionResult> Index(DateTime checkin, DateTime checkout)
        {
            if (checkin > DateTime.Now && checkout > DateTime.Now.AddDays(1))
            {
                var giris = checkin.ToString("yyyy-MM-dd");
                var cikis = checkout.ToString("yyyy-MM-dd");

                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com18.p.rapidapi.com/stays/search?locationId=eyJjaXR5X25hbWUiOiJOZXcgWW9yayIsImNvdW50cnkiOiJVbml0ZWQgU3RhdGVzIiwiZGVzdF9pZCI6IjIwMDg4MzI1IiwiZGVzdF90eXBlIjoiY2l0eSJ9&checkinDate={giris}&checkoutDate={cikis}"),
                    Headers =
                    {
                        { "X-RapidAPI-Key", "f2f44c934dmshe07f0a09554c0a1p18783fjsnbd199f9b1d35" },
                        { "X-RapidAPI-Host", "booking-com18.p.rapidapi.com" },
                    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var bookingModel = JsonConvert.DeserializeObject<BookingModel>(body);
                    return View(bookingModel);
                }
            } else
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com18.p.rapidapi.com/stays/search?locationId=eyJjaXR5X25hbWUiOiJOZXcgWW9yayIsImNvdW50cnkiOiJVbml0ZWQgU3RhdGVzIiwiZGVzdF9pZCI6IjIwMDg4MzI1IiwiZGVzdF90eXBlIjoiY2l0eSJ9&checkinDate={DateTime.Now.ToString("yyyy-MM-dd")}&checkoutDate={DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")}"),
                    Headers =
                    {
                        { "X-RapidAPI-Key", "f2f44c934dmshe07f0a09554c0a1p18783fjsnbd199f9b1d35" },
                        { "X-RapidAPI-Host", "booking-com18.p.rapidapi.com" },
                    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var bookingModel = JsonConvert.DeserializeObject<BookingModel>(body);
                    return View(bookingModel);
                }
            }
        }
    }
}

RapidApi/RapidApiConsume.Web/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiConsume.Web.Models;

namespace RapidApiConsume.Web.Controllers
{
    public class ExchangeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://booking-com.p.rapidapi.com/v1/metadata/exchange-rates?locale=en-gb&currency=TRY"),
                Headers =
                {
                    { "X-RapidAPI-Key", "630ce9cc86msh271c60cffe62d5ep1b514djsn0fe292593744" },
                    { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                var exchangeModel = JsonConvert.DeserializeObject<ExchangeModel>(body);
                return View(exchangeModel.exchange_rates.ToList());
            }
        }
    }
}

RapidApi/RapidApiConsume.Web/Controllers/ImdbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiConsume.Web.Models;

namespace RapidApiConsume.Web.Controllers
{
    public class ImdbController : Controller
    {
        public async Task<IActionResult> Index()
        {
            // Bu alannı Rapid Api sitesinden aldık
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://imdb-top-100-movies.p.rapidapi.com/"),
                Headers =
                {
                    { "X-RapidAPI-Key", "f2f44c934dmshe07f0a09554c0a1p18783fjsnbd199f9b1d35" },
                    { "X-RapidAPI-Host", "imdb-top-100-movies.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();

                // Bu alanı biz ekledik. Gelen json veriyi nesne'ye dönüştürdük ve view'e gönderdik.
                var imdbModel = JsonConvert.DeserializeObject<List<ImdbModel>>(body);
                return View(imdbModel);
            }
        }
    }
}

RapidApi/RapidApiConsume.Web/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiConsume.Web.Models;

namespace RapidApiConsume.Web.Controllers
{
    public class WeatherController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://yahoo-weather5.p.rapidapi.com/weather?location=Ankara&format=json&u=f"),
                Headers =
                {
                    { "X-RapidAPI-Key", "f2f44c934dmshe07f0a09554c0a1p18783fjsnbd199f9b1d35" },
                    { "X-RapidAPI-Host", "yahoo-weather5.p.rapidapi.com" },
                },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                var weatherModel = JsonConvert.DeserializeObject<WeatherModel>(body);
                return View(weatherModel);
            }
        }
    }
}

RapidApi/RapidApiConsume.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RapidApiConsume.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RapidApiConsume.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RapidApiConsume.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imdb" asp-action="Index">Imbd</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exchange" asp-action="Index">Exchange</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Otel Listesi-Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Hava Durumu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RapidApiConsume.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>